apiVersion: getambassador.io/v3alpha1
kind:  Mapping
metadata:
  name: {{ include "ps-admin.fullname" . }}
spec:
  prefix: /admin
  rewrite: /admin
  service: ps-admin
  hostname: {{.Values.config.host}}
  bypass_auth: {{.Values.config.bypass_auth}}