apiVersion: getambassador.io/v3alpha1
kind:  Mapping
metadata:
  name: {{ include "ps-sync.fullname" . }}
spec:
  prefix: /sync
  rewrite: /sync
  service: ps-sync
  hostname: {{.Values.config.host}}
  bypass_auth: {{.Values.config.bypass_auth}}