replicaCount: 1
ps-admin:
  image:
    tag: 1-0
ps-auth:
  image:
    tag: 1-0
ps-sync:
  image:
    tag: 1-0
ps-pricing:
  image:
    tag: 1-0
ps-catalogue:
  image:
    tag: 1-0
ps-amqp-proxy:
  image:
    tag: 1-0
ps-database-migration:
  image:
    tag: 1-0
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts:
  - host: chart-example.local
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
