apiVersion: v1
kind: Secret
metadata:
  name: "amqp-params"
  labels:
    {{- include "ps-setup.labels" . | nindent 4 }}
type: Opaque
data:
  CLOUDAMQP_URL: {{ .Values.cloudAmqpUrl | b64enc | quote }}