apiVersion: v1
kind: Secret
metadata:
  name: "security-service-params"
  labels:
    {{- include "ps-setup.labels" . | nindent 4 }}
type: Opaque
data:
  SECURITY_SERVICE_APP_NAME: {{ .Values.securityServiceParams.appName | b64enc | quote }}
  SECURITY_SERVICE_REGION: {{ .Values.securityServiceParams.region | b64enc | quote }}
  SECURITY_SERVICE_PRIVATE_KEY: {{ .Values.securityServiceParams.privateKey | b64enc | quote }}