apiVersion: getambassador.io/v3alpha1
kind:  Mapping
metadata:
  name: {{ include "ps-pricing.fullname" . }}
spec:
  prefix: /pre
  rewrite: /pre
  service: ps-pricing
  hostname: {{.Values.config.host}}
  bypass_auth: {{.Values.config.bypass_auth}}